### PR TITLE
feat/fix/chore: various improvements

### LINKED ISSUE #14: header improvements
- [x] make Buffer::vector,string functions `const`
- [x] include ordering? remove `extern "C"` from extism.h include
- [x] Review many class variables being exposed `public`
- [x] Review object passing such as `std::vector` being passed around by value
- [x] Bump to C++ 17, replace `ManifestKey` with `std::optional`
- [x] Consider making extism.h a private dependency instead of a public one
- [x] Consider making json/json.h a private dependency instead of a public one

### PR DESCRIPTION
**Pull request by G4Vi**
Resolves https://github.com/extism/cpp-sdk/issues/14

feat:
* add `Plugin::reset`
* implement `WasmSourceBytes`

fix:
* Manifest: serialize header values correctly
* current_plugin - when outputting, check against output range correctly
* Function namespace constructor - actually construct

chore:
* protect various class members
* move non-initializer list constructors out of header
* reduce copying with std::move
* bump to C++ 17
* remove `ManifestKey`, the stl containers and `std::optional` are sufficient
* use `std::unique_ptr` to more safely manage `Plugin`'s `ExtismPlugin` lifetime
* make `std::string` no longer required for plugin calls. The duplication introduced can be removed with `std::string_view` if https://github.com/extism/extism/issues/646 is accepted and implemented
* make jsoncpp a private dependency. This improves build times and makes the cpp-sdk not opinionated about what json library the user uses, if any.
* use `size_t` instead of `ExtismSize` when referring to items in native memory / not using libextism

### CODE REVIEW

File: src/current_plugin.cpp [hunk 1]
```diff
@@ -1,46 +1,42 @@
...
-void CurrentPlugin::output(const std::string &s, size_t index) {
+void CurrentPlugin::output(const std::string &s, size_t index) const {
   this->output((const uint8_t *)s.c_str(), s.size(), index);
 }
 
-void CurrentPlugin::output(const uint8_t *bytes, size_t len, size_t index) {
-  if (index < this->nInputs) {
+void CurrentPlugin::output(const uint8_t *bytes, size_t len,
+                           size_t index) const {
+  if (index < this->nOutputs) {
```
Comment (zshipko) [inline src/current_plugin.cpp:34]: Should we do something if the index is out of bounds?

**Review by zshipko — APPROVED** [review]
Looks good!

File: src/current_plugin.cpp (hunk 1 above)
Comment (G4Vi) [reply src/current_plugin.cpp:34]: The output functions now return a `bool`.

Comment (zshipko) [reply src/current_plugin.cpp:34]: Nice!

**Review by zshipko — APPROVED** [review]
